var instiData = 
[
    {
      "institutionName": "Dental Care Center Bhubaneswar",
      "address": "Plot 214, Lane 14, AIIMS Nagar, Near AIIMS Hospital, Patrapada, Bhubaneswar . pin: 751019",
      "City": "Bhubaneswar",
      "State": "Odisha",
      "pinCode": 751019,
      "personName": "Dr Sangeeta Das",
      "specialities": "General Dentist",
      "type": "BDS",
      "experience": 9
    },
    {
      "institutionName": "Smile O Care",
      "address": "P79, CIT SchmemVIIM, Kankurgachi, Kolkata 700054",
      "City": "Kolkata",
      "State": "West Bengal",
      "pinCode": 700054,
      "personName": "Dr Abhay Sonthalia",
      "specialities": "Prosthodontist and Implantologist",
      "type": "MDS, BDS",
      "experience": 18
    },
    {
      "institutionName": "Smile O Care",
      "address": "P79, CIT SchmemVIIM, Kankurgachi, Kolkata 700054",
      "City": "Kolkata",
      "State": "West Bengal",
      "pinCode": 700054,
      "personName": "Dr Neha Shah",
      "specialities": "Oral & Maxillifacial Pathologist",
      "type": "MDS, BDS",
      "experience": 17
    },
    {
      "institutionName": "Spandan Dental Cure",
      "address": "Near G. T. Road Shibpur",
      "City": "Howrah",
      "State": "West Bengal",
      "pinCode": 711102,
      "personName": "Dr. Anuran Ghosh Mondal",
      "specialities": "Dentist",
      "type": "BDS",
      "experience": 10
    },
    {
      "institutionName": "Magadh Oro Dental & Orthodontic Clinic",
      "address": "K108, P C Colony, Hanuman Nagar,",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 800020,
      "personName": "Dr. Archana Rani",
      "specialities": "Cosmetic Dentist",
      "type": "BDS",
      "experience": 16
    },
    {
      "institutionName": "Magadh Oro Dental & Orthodontic Clinic",
      "address": "K108, P C Colony, Hanuman Nagar,",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 800020,
      "personName": "Dr. Abhishek Kumar",
      "specialities": "Implantologist",
      "type": "BDS",
      "experience": 18
    },
    {
      "institutionName": "Magadh Oro Dental & Orthodontic Clinic",
      "address": "K108, P C Colony, Hanuman Nagar,",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 800020,
      "personName": "Dr. Ritesh Vatsa",
      "specialities": "Oral & Maxillofacial Surgeon",
      "type": "BDS, MDS",
      "experience": 14
    },
    {
      "institutionName": "Magadh Oro Dental & Orthodontic Clinic",
      "address": "K108, P C Colony, Hanuman Nagar,",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 800020,
      "personName": "Dr. Lav Kumar",
      "specialities": "Prosthodontist",
      "type": "BDS, MDS",
      "experience": 16
    },
    {
      "institutionName": "Magadh Oro Dental & Orthodontic Clinic",
      "address": "K108, P C Colony, Hanuman Nagar,",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 800020,
      "personName": "Dr. Deepankar",
      "specialities": "Pediatric Dentist",
      "type": "BDS, MDS",
      "experience": 11
    },
    {
      "institutionName": "Magadh Oro Dental - Implant & Orthodontic Clinic",
      "address": "Flat No 101, Mateshwari Residency, Near Patna Central School",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 800027,
      "personName": "Dr. Archana Rani",
      "specialities": "Cosmetic Dentist",
      "type": "BDS",
      "experience": 16
    },
    {
      "institutionName": "Magadh Oro Dental - Implant & Orthodontic Clinic",
      "address": "Flat No 101, Mateshwari Residency, Near Patna Central School",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 800027,
      "personName": "Dr. Abhishek Kumar",
      "specialities": "Implantologist",
      "type": "BDS",
      "experience": 18
    },
    {
      "institutionName": "Magadh Oro Dental - Implant & Orthodontic Clinic",
      "address": "Flat No 101, Mateshwari Residency, Near Patna Central School",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 800027,
      "personName": "Dr. Ritesh Vatsa",
      "specialities": "Oral & Maxillofacial Surgeon",
      "type": "BDS, MDS",
      "experience": 14
    },
    {
      "institutionName": "Magadh Oro Dental - Implant & Orthodontic Clinic",
      "address": "Flat No 101, Mateshwari Residency, Near Patna Central School",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 800027,
      "personName": "Dr. Lav Kumar",
      "specialities": "Prosthodontist",
      "type": "BDS, MDS",
      "experience": 16
    },
    {
      "institutionName": "Magadh Oro Dental - Implant & Orthodontic Clinic",
      "address": "Flat No 101, Mateshwari Residency, Near Patna Central School",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 800027,
      "personName": "Dr. Deepankar",
      "specialities": "Pediatric Dentist",
      "type": "BDS, MDS",
      "experience": 11
    },
    {
      "institutionName": "Kiran Poly Clinic",
      "address": "Mustafapur, Danapur Khagaul Road, Khagaul",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 801105,
      "personName": "Dr. Nishant Kumar Tewari",
      "specialities": "Oral & Maxillofacial Surgery",
      "type": "MDS",
      "experience": 14
    },
    {
      "institutionName": "Kiran Poly Clinic",
      "address": "Mustafapur, Danapur Khagaul Road, Khagaul",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 801105,
      "personName": "Dr. Sushmita Tiwari",
      "specialities": "Dental Sugeon",
      "type": "BDS",
      "experience": 9
    },
    {
      "institutionName": "T-Care Dental Clinic",
      "address": "68A Tiljala Road, Kolkata -700046",
      "City": "Kolkata",
      "State": "West Bengal",
      "pinCode": 700046,
      "personName": "Dr. Tabinda Hossain",
      "specialities": "Orthodontics and Dentofacial Orthopedics",
      "type": "MDS",
      "experience": 6
    },
    {
      "institutionName": "IVORY DENTAL CLINIC",
      "address": "2/A, MOTIJHIL AVENUE, DUMDUM, KOLKATA-74",
      "City": "Kolkata",
      "State": "West Bengal",
      "pinCode": 700074,
      "personName": "Dr. Rumela Ghosh",
      "specialities": "Dental",
      "type": "BDS, MDS",
      "experience": 10
    },
    {
      "institutionName": "Picasso Dental Studio",
      "address": "Flat-2, 12/1 Hungerford Street(Picasso Bithi)",
      "City": "Kolkata",
      "State": "West Bengal",
      "pinCode": 700017,
      "personName": "Dr Soham Chatterjee",
      "specialities": "Periodontist, laser specialist and Implantologist",
      "type": "MDS",
      "experience": 9
    },
    {
      "institutionName": "DentRelief Dental Clinic",
      "address": "131, Chittaranjan Avenue, beside Monginis",
      "City": "Kolkata",
      "State": "West Bengal",
      "pinCode": 700073,
      "personName": "Dr. Kashif Ahmed Shamsi",
      "specialities": "Implantologist, Endodontist",
      "type": "BDS",
      "experience": 9
    },
    {
      "institutionName": "Facio-max dental clinic",
      "address": "Shop no 3,Radha complex Khelgaon chowk,Dipatoli,Ranchi 834012",
      "City": "Ranchi",
      "State": "Jharkhand",
      "pinCode": 834012,
      "personName": "Dr Ashish kr Roy",
      "specialities": "Dental surgery",
      "type": "BDS",
      "experience": 3
    },
    {
      "institutionName": "BUDDING SMILE DENTAL CLINIC",
      "address": "Down Town Retail, BLOCK C, SHOP NO F124, Uniworld City, Newtown, New Town, West Bengal 700160",
      "City": "Kolkata",
      "State": "West Bengal",
      "pinCode": 700160,
      "personName": "DR ANISH BHARTI",
      "specialities": "PROSTHODONTIST & IMPLANTOLOGIST",
      "type": "BDS, MDS",
      "experience": 13
    },
    {
      "institutionName": "BUDDING SMILE DENTAL CLINIC",
      "address": "Down Town Retail, BLOCK C, SHOP NO F124, Uniworld City, Newtown, New Town, West Bengal 700160",
      "City": "Kolkata",
      "State": "West Bengal",
      "pinCode": 700160,
      "personName": "DR ANITA CHAUHAN",
      "specialities": "PEDODONTICS & PREVENTIV DENTISTRY",
      "type": "BDS, MDS",
      "experience": 13
    },
    {
      "institutionName": "BUDDING SMILE DENTAL CLINIC",
      "address": "Down Town Retail, BLOCK C, SHOP NO F124, Uniworld City, Newtown, New Town, West Bengal 700160",
      "City": "Kolkata",
      "State": "West Bengal",
      "pinCode": 700160,
      "personName": "DR RUPESH KUMAR SINGH",
      "specialities": "ORTHODONTICS",
      "type": "BDS, MDS",
      "experience": 13
    },
    {
      "institutionName": "BUDDING SMILE DENTAL CLINIC",
      "address": "Down Town Retail, BLOCK C, SHOP NO F124, Uniworld City, Newtown, New Town, West Bengal 700160",
      "City": "Kolkata",
      "State": "West Bengal",
      "pinCode": 700160,
      "personName": "DR ADITI BHARTI",
      "specialities": "CERTIFIED AESTHETIC DENTIST",
      "type": "BDS",
      "experience": 13
    },
    {
      "institutionName": "Patwari Dental Hub",
      "address": "Gudri Market, Dispensary road, Near Mahalaxmi Bhog,Sonari, Jamshedpur (Jharkhand)",
      "City": "Jamshedpur",
      "State": "Jharkhand",
      "pinCode": 831011,
      "personName": "Dr Mukesh Patwari",
      "specialities": "Dental Sugeon",
      "type": "BDS",
      "experience": 10
    },
    {
      "institutionName": "Kastury Clinic",
      "address": "Unit of kasturymedicament pvt ltd 4th floor walking street mall",
      "City": "Ranchi",
      "State": "Jharkhand",
      "pinCode": 834001,
      "personName": "Dr. Kundan tiwari",
      "specialities": "Dental Sugeon",
      "type": "BDS",
      "experience": 12
    },
    {
      "institutionName": "SMM DENTAL CARE HOSPITAL",
      "address": "In front of Mahavir Cancer, Sudha Dairy Farm Road, Colony",
      "City": "Patna",
      "State": "Bihar",
      "pinCode": 801505,
      "personName": "Dr. Farhat Jamal",
      "specialities": "Dental & Oral Surgeon",
      "type": "BDS",
      "experience": 6
    },
    {
      "institutionName": "Harsha Dental",
      "address": "No. 14, 21st Cross, 5th Block, HBR Layout, Bengaluru 560043",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560043,
      "personName": "R. Harsha Vardhan",
      "specialities": "Oral medicine and radiology",
      "type": "BDS,MDS",
      "experience": 10
    },
    {
      "institutionName": "The Dental Clinic",
      "address": "3 , 38th Main, Road, near Bank of India, JP Nagar 6th Phase, Rose Garden, Bengaluru, Karnataka 560078",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560078,
      "personName": "Dr Ahalya K",
      "specialities": "Dental",
      "type": "BDS,",
      "experience": 4
    },
    {
      "institutionName": "Virohana Dental Clinic",
      "address": "#1059, 64th Cross, 18th B Main Road, 5th Block, Rajajinagar, Bengaluru 560010",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560010,
      "personName": "Dr Roshini Shetty",
      "specialities": "Dental",
      "type": "BDS",
      "experience": 12
    },
    {
      "institutionName": "Total Tooth Care",
      "address": "#14/1, 24th Main Road, Opp Bindiya Residency, Near Shoba Tulip Appt, JP Nagar 5th phase, Bengaluru, Karnataka 560078",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560078,
      "personName": "Dr Arthi Mishra",
      "specialities": "Dental",
      "type": "BDS",
      "experience": 11
    },
    {
      "institutionName": "DENTAL FITNESS",
      "address": "Rajajinagar, 1st cross, Chord Rd, behind Shri Karya Siddhi Ganapati Temple, near to Mahalakshmi Metro station, Bovipalya, Rajajinagar, Bengaluru, Karnataka 560086",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560086,
      "personName": "Dr Chandan Jha",
      "specialities": "Dental",
      "type": "BDS",
      "experience": 14
    },
    {
      "institutionName": "Smile Lounge Unique Dental Clinic",
      "address": "VG complex, opposite varun motors, above bank of India 2nd floor, Hesergatta main road, Bagalgunte, Bengaluru, Karnataka 560057",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560057,
      "personName": "Dr Rahul Kothari",
      "specialities": "Dental",
      "type": "BDS",
      "experience": 15
    },
    {
      "institutionName": "Dental square advanced dental care",
      "address": "next to Ganesha Temple, Whitefield, Pattandur Agrahara, Bengaluru, Karnataka 560066",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560066,
      "personName": "Dr Pallavi Nayaka",
      "specialities": "Dental",
      "type": "BDS",
      "experience": 8
    },
    {
      "institutionName": "Dhanvi Dental Clinic",
      "address": "Kukatpally Housing Board Colony, Kukatpally, Hyderabad, Telangana 500085",
      "City": "Hyderabad",
      "State": "Karnataka",
      "pinCode": 500085,
      "personName": "Dr Deepthi",
      "specialities": "Dental",
      "type": "BDS",
      "experience": 10
    },
    {
      "institutionName": "Dental health clinic",
      "City": " Bengaluru",
      "personName": "Dr Venkatesh BG",
      "specialities": "Dental",
      "type": "BDS",
      "experience": 22
    },
    {
      "institutionName": "Life Care Dental Clinic Mysore",
      "address": "2979, 6th Main Rd, Vani Vilas Mohalla, Mysuru, Karnataka 570002",
      "City": "Mysore",
      "State": "Karnataka",
      "pinCode": 570002,
      "personName": "Dr Omprakash Y V",
      "specialities": "Dental (Prosthodontist)",
      "type": "BDS, MDS",
      "experience": 22
    },
    {
      "institutionName": "Skident Multispeciality Dental Clinic",
      "address": "Vishwanath Naganahalli Main Rd, Chinana Layout, Guddadahalli, Hebbal, Bengaluru, Karnataka 560032",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560032,
      "personName": "Dr Kavya Sudhakar",
      "specialities": "Dental",
      "type": "BDS",
      "experience": 8
    },
    {
      "institutionName": "Roots N Crowns Dental Care",
      "address": " 83/11, 4th Main Road Rajparis Apartments, 4th Main Rd, V Block, Anna Nagar, Chennai, Tamil Nadu",
      "City": "Chennai",
      "State": "Tamil Nadu",
      "pinCode": 600040,
      "personName": "Dr.Tamilazhagan",
      "specialities": "Endodontist",
      "type": "BDS, MDS",
      "experience": 14
    },
    {
      "institutionName": "Roots N Crowns Dental Care",
      "address": " 83/11, 4th Main Road Rajparis Apartments, 4th Main Rd, V Block, Anna Nagar, Chennai, Tamil Nadu",
      "City": "Chennai",
      "State": "Tamil Nadu",
      "pinCode": 600040,
      "personName": "Dr. Bhagyalakshmi",
      "specialities": "General & Cosmetic Dentist",
      "type": "BDS",
      "experience": 8
    },
    {
      "institutionName": "Roots N Crowns Dental Care",
      "address": " 83/11, 4th Main Road Rajparis Apartments, 4th Main Rd, V Block, Anna Nagar, Chennai, Tamil Nadu",
      "City": "Chennai",
      "State": "Tamil Nadu",
      "pinCode": 600040,
      "personName": "Dr.Harish",
      "specialities": "Prosthodontist & Implantologist",
      "type": "BDS, MDS",
      "experience": 14
    },
    {
      "institutionName": "Roots N Crowns Dental Care",
      "address": " 83/11, 4th Main Road Rajparis Apartments, 4th Main Rd, V Block, Anna Nagar, Chennai, Tamil Nadu",
      "City": "Chennai",
      "State": "Tamil Nadu",
      "pinCode": 600040,
      "personName": "Dr. Krishnapriya",
      "specialities": "Orthodontist",
      "type": "BDS, MDS",
      "experience": 5
    },
    {
      "institutionName": "Roots N Crowns Dental Care",
      "address": " 83/11, 4th Main Road Rajparis Apartments, 4th Main Rd, V Block, Anna Nagar, Chennai, Tamil Nadu",
      "City": "Chennai",
      "State": "Tamil Nadu",
      "pinCode": 600040,
      "personName": "Dr.Gopinath",
      "specialities": "Orthodontist",
      "type": "BDS, MDS",
      "experience": 8
    },
    {
      "institutionName": "Roots N Crowns Dental Care",
      "address": " 83/11, 4th Main Road Rajparis Apartments, 4th Main Rd, V Block, Anna Nagar, Chennai, Tamil Nadu",
      "City": "Chennai",
      "State": "Tamil Nadu",
      "pinCode": 600040,
      "personName": "Dr.Afrath",
      "specialities": "Oral &Maxillofacial Surgeon",
      "type": "BDS, MDS",
      "experience": 14
    },
    {
      "institutionName": "Roots N Crowns Dental Care",
      "address": " 83/11, 4th Main Road Rajparis Apartments, 4th Main Rd, V Block, Anna Nagar, Chennai, Tamil Nadu",
      "City": "Chennai",
      "State": "Tamil Nadu",
      "pinCode": 600040,
      "personName": "Dr.Kapil Dev",
      "specialities": "Oral &Maxillofacial Surgeon",
      "type": "BDS, MDS",
      "experience": 10
    },
    {
      "institutionName": "Roots N Crowns Dental Care",
      "address": " 83/11, 4th Main Road Rajparis Apartments, 4th Main Rd, V Block, Anna Nagar, Chennai, Tamil Nadu",
      "City": "Chennai",
      "State": "Tamil Nadu",
      "pinCode": 600040,
      "personName": "Dr.Anusha",
      "specialities": "Pedodontist",
      "type": "BDS, MDS",
      "experience": 8
    },
    {
      "institutionName": "Vaishnavi Dental N Orthodontic Center",
      "address": "No 30 , Lakshmamma nilaya munibatshamma ashram road 11Th cross leggare",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560058,
      "personName": "Bhagyalakhsmi RG",
      "specialities": "BDS , cosmetic dental SURGEON",
      "type": "BDS",
      "experience": 11
    },
    {
      "institutionName": "KR Dental Hospital",
      "address": "Dr. PV Raman Building, ChandaNagar , serilingampally",
      "City": "Hyderabad",
      "State": "Andhra Pradesh",
      "pinCode": 500050,
      "personName": "Katta Ravi Chandu",
      "specialities": "Peridontology",
      "type": "BDS, MDS",
      "experience": 5
    },
    {
      "institutionName": "Advanced Dental Care and Orthodontic Centre",
      "address": "Dental Square beside Vinayaka temple , OPP. foyer infinity, behind ITPL, Pattandur agrahara",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560066,
      "personName": "Dental Square,",
      "specialities": "Orthodontics",
      "type": "BDS, MDS",
      "experience": 3
    },
    {
      "institutionName": "Dental Roots Root canal & Implant centre",
      "address": "Root canal & Implant centre 1050/A ,1st floor New Thippasandra Main road Near Vishal Mart Indirangar Bangalore",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560075,
      "personName": "Anju Thomas",
      "specialities": "Designation: Dentist ,Prosthodontist and Oral Implantologist",
      "type": "BDS, MDS",
      "experience": 12
    },
    {
      "institutionName": "Smile Miles\r\n Dental Hospital",
      "address": "103, Kishen Residency(1-11-242/1), Near HPS School, Shyamal Buildings, Sardar Patel Road, Begumpet,",
      "City": "Hyderabad",
      "State": "Andhra Pradesh",
      "pinCode": 560016,
      "personName": "Dr Srikanth Guduguntla",
      "specialities": "periodontist, Dental Surgeon, Professor",
      "type": "BDS, MDS"
    },
    {
      "institutionName": "Shri Guru Raghavendra Dental Speciality",
      "address": "3 , 13/118 Ittamadu main road bsk 3rd Stage",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560085,
      "personName": "Sripada .N",
      "specialities": "BDS",
      "type": "BDS",
      "experience": 17
    },
    {
      "institutionName": "Advanced Dental Care and Orthodontic Centre",
      "address": "Dental Square beside Vinayaka temple , OPP. foyer infinity, behind ITPL, Pattandur agrahara",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560066,
      "personName": "Anju",
      "specialities": "Orthodontics",
      "type": "BDS, MDS",
      "experience": 3
    },
    {
      "institutionName": "V.V. Dental Hospital",
      "address": "Achu Towers, opposite MRF Tyredome, AC-13 (149, 2nd Ave, opp. Saravana Bhavan, AC Block, Anna Nagar, Chennai, Tamil Nadu 600040",
      "City": "Chennai",
      "State": "Tamil Nadu",
      "pinCode": 600040,
      "personName": "Dr. N V Arumugam",
      "specialities": "Oral And MaxilloFacial Surgeon",
      "type": "BDS, MDS",
      "experience": 42
    },
    {
      "institutionName": "V.V. Dental Hospital",
      "address": "Achu Towers, opposite MRF Tyredome, AC-13 (149, 2nd Ave, opp. Saravana Bhavan, AC Block, Anna Nagar, Chennai, Tamil Nadu 600040",
      "City": "Chennai",
      "State": "Tamil Nadu",
      "pinCode": 600040,
      "personName": "Dr. Ranjani Iyer",
      "specialities": "DENTAL SURGEON",
      "type": "BDS",
      "experience": 41
    },
    {
      "institutionName": "Jain Dental Centre",
      "address": "A-101, Brigade Majestic, Kalidasa marg, above Airtel, Gandhinagar, Bangalore",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560009,
      "personName": "Dr. Abhishek Lamechwal",
      "specialities": "Prosthodontist",
      "type": "BDS, MDS",
      "experience": 2
    },
    {
      "institutionName": "Jain Dental Centre",
      "address": "A-101, Brigade Majestic, Kalidasa marg, above Airtel, Gandhinagar, Bangalore",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560009,
      "personName": "Dr. Rajesh Lamechwal",
      "specialities": "DENTAL SURGEON",
      "type": "BDS",
      "experience": 35
    },
    {
      "institutionName": "Jain Dental Centre",
      "address": "A-101, Brigade Majestic, Kalidasa marg, above Airtel, Gandhinagar, Bangalore",
      "City": " Bengaluru",
      "State": "Karnataka",
      "pinCode": 560009,
      "personName": "Dr Rishita Lamechwal",
      "specialities": "Oral and Maxillofacial surgeon",
      "type": "BDS",
      "experience": 9
    },
    {
      "institutionName": "DentoFacial and Implant Clinic",
      "address": "NH B-1, Lohia Nagar, Ghaziabad, Uttar Pradesh 201001",
      "City": "Ghaziabad",
      "State": "Uttar Pradesh",
      "pinCode": 201001,
      "personName": "Dr. Nitin Kumar Moral",
      "specialities": "Oral And MaxilloFacial Surgeon",
      "type": "BDS,MDS",
      "experience": 10
    },
    {
      "institutionName": "DentoFacial and Implant Clinic",
      "address": "NH B-1, Lohia Nagar, Ghaziabad, Uttar Pradesh 201001",
      "City": "Ghaziabad",
      "State": "Uttar Pradesh",
      "pinCode": 201001,
      "personName": "Dr. Nidhi Nagar Moral",
      "specialities": "Endodontist",
      "type": "BDS, MDS, FICR (USA)",
      "experience": 8
    },
    {
      "institutionName": "Dr. Nitin Kumar Moral Dentist in Ghaziabad",
      "address": "First Floor, Shop, 6, River Heights Rd, Sehani Khurd, Raj Nagar Extension, Ghaziabad, Uttar Pradesh 201017",
      "City": "Ghaziabad",
      "State": "Uttar Pradesh",
      "pinCode": 201017,
      "personName": "Dr. Nitin Kumar Moral",
      "specialities": "Oral And MaxilloFacial Surgeon",
      "type": "BDS, MDS",
      "experience": 10
    },
    {
      "institutionName": "Dr. Nitin Kumar Moral Dentist in Ghaziabad",
      "address": "First Floor, Shop, 6, River Heights Rd, Sehani Khurd, Raj Nagar Extension, Ghaziabad, Uttar Pradesh 201017",
      "City": "Ghaziabad",
      "State": "Uttar Pradesh",
      "pinCode": 201017,
      "personName": "Dr. Nidhi Nagar Moral",
      "specialities": "Endodontist",
      "type": "BDS, MDS, FICR (USA)",
      "experience": 8
    },
    {
      "institutionName": "LOTUS DENTAL AND MULTISPECIALITY CLINIC",
      "address": "GROUND FLOOR, TOWER-6, 04, Lotus Boulevard, Sector 100, Noida, Uttar Pradesh 201304",
      "City": "Noida",
      "State": "Uttar Pradesh",
      "pinCode": 201304,
      "personName": "Dr jayant yadav",
      "specialities": "General dentist",
      "type": "BDS",
      "experience": 15
    },
    {
      "institutionName": "Krishna Dental Clinic",
      "address": "Shop no 112 ground floor, NH-19, opposite Petrol Pump, near Jai ram ashram mandir, Hari Nagar Ashram, New Delhi, Delhi 110014",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110014,
      "personName": "Dr jayant yadav",
      "specialities": "General dentist",
      "type": "BDS",
      "experience": 15
    },
    {
      "institutionName": "Gupta Dental Care & Orthodontic Centre -Najafgarh, Delhi",
      "address": "RZ-16, Roshan Garden, Bhai Bharat singh Marg, Tuda Mandi Chowk, Najafgarh",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110043,
      "personName": "Dr. Ankur Gupta",
      "specialities": "General dentist",
      "type": "BDS, MDS",
      "experience": 11
    },
    {
      "institutionName": "Gupta Dental Care & Orthodontic centre -Dwarka sec 5, Delhi",
      "address": "T8 & 9, 3rd floor, HL square building, Dwarka Sec-5 (near Aashirwad chowk)",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110075,
      "personName": "Dr. Ankur Gupta",
      "specialities": "General dentist",
      "type": "BDS, MDS",
      "experience": 11
    },
    {
      "institutionName": "Kaashvi Medident",
      "address": "A-78, sector 49, Noida",
      "City": "Noida",
      "State": "Uttar Pradesh",
      "pinCode": 201301,
      "personName": "Dr Shalini Jain",
      "specialities": "General dentist",
      "type": "BDS, MDS",
      "experience": 20
    },
    {
      "institutionName": "TEVATIA DENTAL CARE",
      "address": "B-83 Janta Flat, (Opp. Madhuban Enclave LIG Flats Gate no-4), Madipur, Delhi",
      "City": "Delhi",
      "State": "Delhi",
      "pinCode": 110063,
      "personName": "DR. SIDDHARTH TEVATIA",
      "specialities": "Periodontist& Implantologist",
      "type": "BDS,MDS",
      "experience": 8
    },
    {
      "institutionName": "Crown and Roots Dental Clinic",
      "address": "L-1/3 (Basement)",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110049,
      "personName": "Dr Kartik Datta",
      "specialities": "Endodontist",
      "type": "BDS, MDS",
      "experience": 11
    },
    {
      "institutionName": "Crown and Roots Dental Clinic",
      "address": "L-1/3 (Basement)",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110049,
      "personName": "Dr Mansi Datta",
      "specialities": "Prosthodontist",
      "type": "BDS,MDS",
      "experience": 11
    },
    {
      "institutionName": "Ishwar Dental Clinic",
      "address": "D-65/226, Lahartara, Varanasi City, Landmark: Near Cantt Railway.",
      "City": "Varanasi",
      "State": "Uttar Pradesh",
      "pinCode": 221002,
      "personName": "Dr. Manish Shrivastav",
      "specialities": "Dental surgeon",
      "type": "B.Sc., B.D.S., P.D.C.R",
      "experience": 18
    },
    {
      "institutionName": "Mukta Dental Clinic",
      "address": "OPPOSITE NEW SATELLITE HOSPITAL HIRAN MAGRI",
      "City": "Udaipur",
      "State": "Rajasthan",
      "pinCode": 313002,
      "personName": "Dr. Rohan Bhatt",
      "specialities": "Dental Surgeon",
      "type": "BDS PGDACR",
      "experience": 13
    },
    {
      "institutionName": "Dr PS Ratta Dental and Implant clinic",
      "address": "AA-22, Shalimar Bagh, Delhi 110088.",
      "City": "Delhi",
      "State": "Delhi",
      "pinCode": 110088,
      "personName": "Dr. Pavneet Singh Ratta",
      "specialities": "General dentist",
      "type": "BDS,MDS",
      "experience": 12
    },
    {
      "institutionName": "JAMMU TEETH CLINIC",
      "address": "First floor opp.Tandoori Tikka Town SIDCO CHOWK BARIBRAHMANA",
      "City": "BariBrahmana",
      "State": "Jammu and Kashmir",
      "pinCode": 181133,
      "personName": "Dr.Muzzaffer Hussain",
      "specialities": "Dental Surgeon",
      "type": "BDS",
      "experience": 10
    },
    {
      "institutionName": "Jammu Teeth Clinic 2.0",
      "address": "Lane opp.AM Hyundai Billal Colony House no 489 Chhani Rama Jammu180015",
      "City": "Jammu",
      "State": "Jammu and Kashmir",
      "pinCode": 180015,
      "personName": "Dr.Muzzaffer Hussain",
      "specialities": "Dental Surgeon",
      "type": "BDS",
      "experience": 10
    },
    {
      "institutionName": "Tooth Essentials Multispeciality Dental Clinic.",
      "address": "C3/11 Ground Floor, Janakpuri, New Delhi 110058",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110058,
      "personName": "Dr Gagan Khanna",
      "specialities": "Prosthodontist and Implantologist",
      "type": "BDS, MDS",
      "experience": 19
    },
    {
      "institutionName": "City Dental - E-986",
      "address": "E-986, Block E, Saraswati Vihar, Pitampura, Delhi, 110034",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110034,
      "personName": "Dr Kapil Garg",
      "specialities": "Periodontology and Implantology",
      "type": "BDS",
      "experience": 15
    },
    {
      "institutionName": "City Dental - E-986",
      "address": "E-986, Block E, Saraswati Vihar, Pitampura, Delhi, 110034",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110034,
      "personName": "Dr Anjali Aggarwal",
      "specialities": "Dentist",
      "type": "B.D.S.",
      "experience": 11
    },
    {
      "institutionName": "City Dental - HU -84",
      "address": "HU -84, near Krishna Medicos, Pitampura, Delhi, 110034",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110034,
      "personName": "Dr Kapil Garg",
      "specialities": "Periodontology and Implantology",
      "type": "B.D.S.",
      "experience": 15
    },
    {
      "institutionName": "City Dental - HU -84",
      "address": "HU -84, near Krishna Medicos, Pitampura, Delhi, 110034",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110034,
      "personName": "Dr Anjali Aggarwal",
      "specialities": "Dentist",
      "type": "BDS, MDS",
      "experience": 11
    },
    {
      "institutionName": "MISHRA'S CLINIC",
      "address": "B-361, 362 LAJPAT NAGAR NEAR JAGDAMBA SWEETS SAHIBABAD ,",
      "City": "Ghaziabad",
      "State": "UTTAR PRADESH",
      "pinCode": 201005,
      "personName": "Dr Manoj Mishra",
      "specialities": "DENTIST OR DENTAL SURGEON",
      "type": "BDS, MDS",
      "experience": 14
    },
    {
      "institutionName": "SHREE KERISHNA MULTI DENTAL CLINIC & IMPLANT CENTER",
      "address": "3rd Floor, 334,335, Avadh Pride, Opp Metro Piller No- P139, Near Nirant Cross Road, Vastral Road, Ahmedabad - 382418",
      "City": "Ahmedabad",
      "State": "Gujarat",
      "pinCode": 382418,
      "personName": "DR.NILESHKUMAR PATEL",
      "specialities": "Dental Surgeon",
      "type": "BDS, MDS",
      "experience": 16
    },
    {
      "institutionName": "KHATRI DENTAL CLINIC",
      "address": "E 6 BHAGWAN DAS NAGAR EAST PUNJABI BAGH NEW DELHI 110026",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110026,
      "personName": "Dr. Priti Khatri",
      "specialities": "Dental Surgeon",
      "type": "BDS, MDS",
      "experience": 23
    },
    {
      "institutionName": "KHATRI DENTAL CLINIC",
      "address": "E 6 BHAGWAN DAS NAGAR EAST PUNJABI BAGH NEW DELHI 110026",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110026,
      "personName": "Dr. Manish Khatri",
      "specialities": "Prosthodontist and Implantologist",
      "type": "BDS, MDS",
      "experience": 25
    },
    {
      "institutionName": "KHATRI DENTAL CLINIC",
      "address": "E 6 BHAGWAN DAS NAGAR EAST PUNJABI BAGH NEW DELHI 110026",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110026,
      "personName": "Dr. Rajiv Kumar Gupta",
      "specialities": "Dental Surgeon",
      "type": "BDS, MDS",
      "experience": 11
    },
    {
      "institutionName": "KHATRI DENTAL CLINIC",
      "address": "E 6 BHAGWAN DAS NAGAR EAST PUNJABI BAGH NEW DELHI 110026",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110026,
      "personName": "Dr. Vikram Kapoor",
      "specialities": "Prosthodontists",
      "type": "BDS, MDS",
      "experience": 19
    },
    {
      "institutionName": "KHATRI DENTAL CLINIC",
      "address": "E 6 BHAGWAN DAS NAGAR EAST PUNJABI BAGH NEW DELHI 110026",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110026,
      "personName": "Dr. Jatin Kalra",
      "specialities": "Oral Surgeon & Implantologist",
      "type": "BDS",
      "experience": 23
    },
    {
      "institutionName": "KHATRI DENTAL CLINIC",
      "address": "E 6 BHAGWAN DAS NAGAR EAST PUNJABI BAGH NEW DELHI 110026",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110026,
      "personName": "Dr. Vipin Behrani",
      "specialities": "Orthodontist",
      "type": "BDS, MDS",
      "experience": 23
    },
    {
      "institutionName": "KHATRI DENTAL CLINIC",
      "address": "E 6 BHAGWAN DAS NAGAR EAST PUNJABI BAGH NEW DELHI 110026",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110026,
      "personName": "Dr. Deepak Punhani",
      "specialities": "Dental Surgeon",
      "type": "BDS, MDS",
      "experience": 24
    },
    {
      "institutionName": "KHATRI DENTAL CLINIC",
      "address": "E 6 BHAGWAN DAS NAGAR EAST PUNJABI BAGH NEW DELHI 110026",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110026,
      "personName": "Dr. Atul Gupta",
      "specialities": "Endodontist",
      "type": "MDS",
      "experience": 24
    },
    {
      "institutionName": "Rama Dental Clinic",
      "address": "A-2/29, Main Nehru Gali, Main Rd, West Sant Nagar, Burari, Delhi, 110084",
      "City": "Delhi",
      "State": "Delhi",
      "pinCode": 110084,
      "personName": "Dr. Himanshu Tanwar",
      "specialities": "Dental Surgeon",
      "type": "BDS",
      "experience": 5
    },
    {
      "institutionName": "Dr. Gyan's Dental Speciality clinic",
      "address": "F-25/98,Sector-7,Near Ayodhya chowk Rohini -Delhi 110085",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110085,
      "personName": "Dr. Gyan Chand Jain",
      "specialities": "ORAL SURGERY",
      "type": "BDS,MDS",
      "experience": 25
    },
    {
      "institutionName": "Dr. Gyan's Dental Speciality clinic",
      "address": "F-25/98,Sector-7,Near Ayodhya chowk Rohini -Delhi 110085",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110085,
      "personName": "DR. REETA JAIN",
      "specialities": "Prosthodontics",
      "type": "M.D.S.",
      "experience": 25
    },
    {
      "institutionName": "DENTAL HUB",
      "address": "14/4 Girdhar Marg Malviyanagar.",
      "City": "Jaipur",
      "State": "Rajasthan",
      "pinCode": 302017,
      "personName": "Dr Vikas Jharwal",
      "specialities": "Orthodontics",
      "type": "MDS",
      "experience": 15
    },
    {
      "institutionName": "Shree Ji Dental Clinic",
      "address": "Near Gandhi circle Purani subji market Pin. 326502",
      "City": "Bhawani Mandi",
      "State": "Rajasthan",
      "pinCode": 326502,
      "personName": "Dr Shubham Jain",
      "specialities": "Dental Surgeon",
      "type": "MDS",
      "experience": 6
    },
    {
      "institutionName": "ABHA TOOTH WORLD",
      "address": "Near Chandra Medical, Janta Colony, Vaishi Nagar",
      "City": "Ajmer",
      "State": "Rajasthan",
      "pinCode": 305004,
      "personName": "Dr.Mohit Chaturvedi.",
      "specialities": "Orthodontics and Dentofacial Orthopedics) and Implantologist",
      "type": "MDS",
      "experience": 11
    },
    {
      "institutionName": "ABHA TOOTH WORLD",
      "address": "Near Chandra Medical, Janta Colony, Vaishi Nagar",
      "City": "Ajmer",
      "State": "Rajasthan",
      "pinCode": 305004,
      "personName": "Dr.Neha Chaturvedi",
      "specialities": "Endodontics and Conservative Dentistry and cosmetic surgeon",
      "type": "BDS",
      "experience": 8
    },
    {
      "institutionName": "Dr Batra's Dentistree",
      "address": "FF-146, S9 Square, above patanjali Store, beside lilleria party plot,sama savli road, vemali , Vadodara,",
      "City": "Vadodara",
      "State": "Gujarat",
      "pinCode": 390008,
      "personName": "Dr Mira Batra",
      "specialities": "Periodontics",
      "type": "BDS",
      "experience": 13
    },
    {
      "institutionName": "Dr Batra's Dentistree",
      "address": "FF-146, S9 Square, above patanjali Store, beside lilleria party plot,sama savli road, vemali , Vadodara,",
      "City": "Vadodara",
      "State": "Gujarat",
      "pinCode": 390008,
      "personName": "Dr Samir Batra",
      "specialities": "Orthodontic",
      "type": "BDS",
      "experience": 15
    },
    {
      "institutionName": "Dr. Sharma’s Dental Hub",
      "address": "SCO 1130 first floor, sector 22B chandigarh 160022",
      "City": "Chandigarh",
      "State": "Chandigarh",
      "pinCode": 160022,
      "personName": "Dr. Puneet sharma",
      "specialities": "Orthodontics",
      "type": "BDS",
      "experience": 5
    },
    {
      "institutionName": "Teeth and smile dental clinic",
      "address": "T1 1204 Panchsheel Pratishtha Sector75 Noida",
      "City": "Noida",
      "State": "Uttar Pradesh",
      "pinCode": 201301,
      "personName": "Dr Namrata Singhal",
      "specialities": "General Dentistry",
      "type": "BDS",
      "experience": 15
    },
    {
      "institutionName": "Chauhan Dental Clinic (Jabalpur)",
      "address": "Near Allahabad ATM, Dhanwantri Nagar, Chauraha, Jabalpur, Madhya Pradesh 482003,",
      "City": "Jabalpur",
      "State": "Madhya Pradesh",
      "pinCode": 482003,
      "personName": "Dr Sunil singh chauhan",
      "specialities": "Dental Surgeon",
      "type": "BDS",
      "experience": 25
    },
    {
      "institutionName": "Chauhan Dental Clinic (Jabalpur)",
      "address": "Near Allahabad ATM, Dhanwantri Nagar, Chauraha, Jabalpur, Madhya Pradesh 482003,",
      "City": "Jabalpur",
      "State": "Madhya Pradesh",
      "pinCode": 482003,
      "personName": "Dr Heena Chauhan",
      "specialities": "Dental Surgeon",
      "type": "BDS, MDS",
      "experience": 25
    },
    {
      "institutionName": "Chauhan Dental Clini (Aaga Chowk)",
      "address": "Rajul Complex ,Aaga Chowk, Madhya Pradesh 482002",
      "City": "Aaga Chowk",
      "State": "Madhya Pradesh",
      "pinCode": 482002,
      "personName": "Dr Sunil singh chauhan",
      "specialities": "Dental Surgeon",
      "type": "MDS",
      "experience": 25
    },
    {
      "institutionName": "Chauhan Dental Clini (Aaga Chowk)",
      "address": "Rajul Complex ,Aaga Chowk, Madhya Pradesh 482002",
      "City": "Aaga Chowk",
      "State": "Madhya Pradesh",
      "pinCode": 482002,
      "personName": "Dr Heena Chauhan",
      "specialities": "Dental Surgeon",
      "type": "BDS",
      "experience": 25
    },
    {
      "institutionName": "Agrawal Dental Clinic",
      "address": "3rd Floor, Shriji Darshan Complex, Iscon Temple, Karamsad Rd, Patel Society, Vallabh Vidyanagar, Anand, Gujarat 388120",
      "City": "Anand",
      "State": "Gujarat",
      "pinCode": 388120,
      "personName": "Dr. Vinit Agarwal",
      "specialities": "Dental Surgeon & Implantologist",
      "type": "BDS",
      "experience": 11
    },
    {
      "institutionName": "Lifetime Smilez Orthodontic & Dental Practice",
      "address": "1145 D1 vasant kunj new delhi 110070",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110070,
      "personName": "Dr Lakshya sharma",
      "specialities": "Orthodontics and Implantology",
      "type": "MDS, BDS",
      "experience": 19
    },
    {
      "institutionName": "GUPTA DENTAL HOSPITAL",
      "address": "IGNATURE TOWER, NEAR JAIN BHAWAN, SC NO 10 ALWAR",
      "City": "ALWAR",
      "State": "RAJASTHAN",
      "pinCode": 301001,
      "personName": "Dr. Amit Kumar Gupta",
      "specialities": "PEDODONTICS",
      "type": "BDS",
      "experience": 13
    },
    {
      "institutionName": "Dental Remedies",
      "address": "D-55 G1 Upper Ground floor Chander Nagar Infront of BEL Officer's Colony gate Ghaziabad",
      "City": "Ghaziabad",
      "State": "Uttar Pradesh",
      "pinCode": 201011,
      "personName": "Dr Gaurav Bandil",
      "specialities": "DENTIST",
      "type": "BDS",
      "experience": 14
    },
    {
      "institutionName": "Family Dental Care",
      "address": "Plot no- 122/S3, Kaling Marg, Sector 4, Vaishali, Ghaziabad, Uttar Pradesh 201010",
      "City": "Ghaziabad",
      "State": "Uttar Pradesh",
      "pinCode": 201010,
      "personName": "Dr Rahul Rana",
      "specialities": "Aesthetic Dentistry, Root Canals and Smile make over",
      "type": "BDS",
      "experience": 5
    },
    {
      "institutionName": "Manas Orthodontic Center",
      "address": "D-52, near Medical College Auditorium, Sector-D, Shastri Nagar, Jodhpur, Rajasthan 342001",
      "City": "Jodhpur",
      "State": "Rajasthan",
      "pinCode": 342001,
      "personName": "Dr. Saurabh Gandhi",
      "specialities": "Orthodontics",
      "type": "BDS, MDS",
      "experience": 15
    },
    {
      "institutionName": "Keep Smiling Dental Orthodontic & Implant Cen",
      "address": "11,DDA Market CSC no 8, near DAV PUBLIC SCHOOL, Sector 7, Rohini, Delhi 110085",
      "City": "Rohini",
      "State": "Delhi",
      "pinCode": 110085,
      "personName": "Dr Shikha Malik",
      "specialities": "Dental surgeon",
      "type": "BDS",
      "experience": 13
    },
    {
      "institutionName": "Magnus Dental Clinic & Implant Centre",
      "address": "3D, Block D, New Industrial Twp 3, New Industrial Township, Faridabad, Haryana 121001",
      "City": "Faridabad",
      "State": "Haryana",
      "pinCode": 121001,
      "personName": "Dr. M Aslam Rehman",
      "specialities": "Dental Surgeon",
      "type": "MDS",
      "experience": 15
    },
    {
      "institutionName": "The Xcel Dental",
      "address": "Opposite Shiv Vihar Mandir, Gurudwara Road, Shiv Vihar, Karala, New Delhi - 110081",
      "City": "Karala",
      "State": "New Delhi",
      "pinCode": 110081,
      "personName": "Dr. Sikander Chouhan",
      "specialities": "Implantologist & Endodontist",
      "type": "BDS",
      "experience": 3
    },
    {
      "institutionName": "The Xcel Dental",
      "address": "Opposite Shiv Vihar Mandir, Gurudwara Road, Shiv Vihar, Karala, New Delhi - 110081",
      "City": "Karala",
      "State": "New Delhi",
      "pinCode": 110081,
      "personName": "Dr. Deepak Chopra",
      "specialities": "Prosthodontist and implantologist",
      "type": "BDS, MDS",
      "experience": 18
    },
    {
      "institutionName": "The Xcel Dental",
      "address": "Opposite Shiv Vihar Mandir, Gurudwara Road, Shiv Vihar, Karala, New Delhi - 110081",
      "City": "Karala",
      "State": "New Delhi",
      "pinCode": 110081,
      "personName": "Dr. Nawaz",
      "specialities": "Endodontist",
      "type": "BDS",
      "experience": 7
    },
    {
      "institutionName": "Dr Varshneys Dentocare",
      "address": "SCO 74, First Floor, Sector 46C, Chandigarh, 160047",
      "City": "Chandigarh",
      "State": "Chandigarh",
      "pinCode": 160047,
      "personName": "Dr. Gaurav Varshney",
      "specialities": "Prosthodontist and implantologist",
      "type": "BDS,MPH",
      "experience": 11
    },
    {
      "institutionName": "Kamal Dental Clinic, Orthodontic & Implant center",
      "address": "Balaji town,balita road,kunhadi",
      "City": "Kota",
      "State": "Rajasthan",
      "pinCode": 324008,
      "personName": "DR VIPIN AGRAWAL",
      "specialities": "DENTAL SURGEON",
      "type": "MDS",
      "experience": 10
    },
    {
      "institutionName": "Smile Of India ",
      "address": "Crossings Republik Road NS VIP Complex",
      "City": "Greater Noida",
      "State": "Uttar Pradesh",
      "pinCode": 201016,
      "personName": "Dr. Shashi Bhal Maurya",
      "specialities": "Implantologist",
      "type": "BDS",
      "experience": 8
    },
    {
      "institutionName": "Smile Of India ",
      "address": "Crossings Republik Road NS VIP Complex",
      "City": "Greater Noida",
      "State": "Uttar Pradesh",
      "pinCode": 201016,
      "personName": "Dr. Aditi Kumari",
      "specialities": "DENTIST",
      "type": "BDS",
      "experience": 4
    },
    {
      "institutionName": "The Dental Home",
      "address": "#820, Sector 9, Panchkula",
      "City": "Panchkula",
      "State": "Haryana",
      "pinCode": 134109,
      "personName": "Dr. Ankush Jindal",
      "specialities": "Preventive Care",
      "type": "BDS, MDS",
      "experience": 13
    },
    {
      "institutionName": "The Dental Home",
      "address": "#820, Sector 9, Panchkula",
      "City": "Panchkula",
      "State": "Haryana",
      "pinCode": 134109,
      "personName": "Dr. Shina Jindal",
      "specialities": "Prosthodontist",
      "type": "BDS, MDS",
      "experience": 11
    },
    {
      "institutionName": "SAINI DENTAL CLINIC",
      "address": "Shop No.2,Shivam Enclave,In Front Of Gulab Bagh",
      "City": "KOTA",
      "State": "RAJASTHAN",
      "pinCode": 324001,
      "personName": "DR.AWADHESH SAINI",
      "specialities": "Implant And Orthodontic",
      "type": "BDS, MDS",
      "experience": 16
    },
    {
      "institutionName": "Vijay dental clinic",
      "address": "Vijay dental clinic,opp taxi stand, bhotia parao, nainital road, Haldwani, Uttrakhand 263139",
      "City": "Haldwani",
      "State": "Uttrakhand",
      "pinCode": 263139,
      "personName": "Dr Reema agrawal",
      "specialities": "DENTAL SURGEON",
      "type": "BDS, MDS",
      "experience": 13
    },
    {
      "institutionName": "Pannus Dental Care (Sector 21)",
      "address": "House no 355 sector 21",
      "City": "Panchkula",
      "State": "Haryana",
      "pinCode": 134116,
      "personName": "Dr Abhishek Pannu",
      "specialities": "Prosthodontics & Implantology",
      "type": "BDS, MDS",
      "experience": 11
    },
    {
      "institutionName": "Pannus Dental Care (Sector 21)",
      "address": "House no 355 sector 21",
      "City": "Panchkula",
      "State": "Haryana",
      "pinCode": 134116,
      "personName": "Dr Manjeet Kaur",
      "specialities": "PEDODONTICS",
      "type": "BDS",
      "experience": 6
    },
    {
      "institutionName": "Pannus Dental Care (Sector 70)",
      "address": "House no. 195",
      "City": "Mohali",
      "State": "Punjab",
      "pinCode": 160071,
      "personName": "Dr Abhishek Pannu",
      "specialities": "Prosthodontics & Implantology",
      "type": "BDS,MDS",
      "experience": 11
    },
    {
      "institutionName": "Pannus Dental Care (Sector 70)",
      "address": "House no. 195",
      "City": "Mohali",
      "State": "Punjab",
      "pinCode": 160071,
      "personName": "Dr Manjeet Kaur",
      "specialities": "PEDODONTICS",
      "type": "BDS",
      "experience": 6
    },
    {
      "institutionName": "Dr Saurabh Dental Clinic & Implant Center",
      "address": "Shop No 1-B, Vinayak Residency, University Rd, Keshav Nagar, Udaipur, Rajasthan 313001",
      "City": "Udaipur",
      "State": "Rajasthan",
      "pinCode": 313001,
      "personName": "Dr. Saurabh Goel",
      "specialities": "DENTAL SURGEON",
      "type": "BDS, MDS",
      "experience": 13
    },
    {
      "institutionName": "Jindal Oro Dental Clinic",
      "address": "Gill road Near Gill Bridge, Adjoining I. T. I. College, Opposite S. B. I. BANK, Ludhiana, Punjab 141003",
      "City": "Ludhiana",
      "State": "Punjab",
      "pinCode": 141003,
      "personName": "Dr. Ramnik Jindal",
      "specialities": "DENTAL SURGEON",
      "type": "BDS, MDS",
      "experience": 19
    },
    {
      "institutionName": "Aashu Dental Clinic",
      "address": "Dr. K.K.Shah's Bunglow, Post Office, behind Navrangpura, Mithakhali, Navrangpura, Ahmedabad, Gujarat 380009",
      "City": "Ahmedabad",
      "State": "Gujarat",
      "pinCode": 380009,
      "personName": "Dr. Manish Shah",
      "specialities": "DENTAL SURGEON",
      "type": "BDS",
      "experience": 26
    },
    {
      "institutionName": "Sachin Arora's Dental And Orthodontic Clinic",
      "address": "K 30 B basement, opposite Balaji Estate, Kalkaji, New Delhi, Delhi 110019",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110019,
      "personName": "Dr Sachin Arora",
      "specialities": "DENTAL SURGEON",
      "type": "BDS",
      "experience": 23
    },
    {
      "institutionName": "The Brij Dental Clinic & Implant Center",
      "address": "F-10, 1st Floor, Akash III complex, 132 Feet Ring Rd, above Hyundai showroom, Naranpura, Ahmedabad, Gujarat 380013",
      "City": "Ahmedabad",
      "State": "Gujarat",
      "pinCode": 380013,
      "personName": "Dr. Brijesh S. Patel",
      "specialities": "DENTAL SURGEON",
      "type": "BDS, MDS",
      "experience": 11
    },
    {
      "institutionName": "Dental Oasis Orthodontic & Dental Clinic",
      "address": "2nd Floor, Western Buisness Center, Above Union Bank of India, 1/6 New Palasia, Indore-452001",
      "City": "Indore",
      "State": "Indore",
      "pinCode": 452001,
      "personName": "Dr. Virag Bhatia",
      "specialities": "Orthodontics",
      "type": "BDS",
      "experience": 15
    },
    {
      "institutionName": "Smile Makers Dental Clinic and Implant Center",
      "address": "103 sai vaastu heights, Next to SBI Seven star lane Service road Opp ganeesham d Near govind yashda Chowk",
      "City": "Pune",
      "State": "Maharastra",
      "pinCode": 411027,
      "personName": "Dr Ashish Bandewar",
      "specialities": "DENTAL SURGEON",
      "type": "BDS, MDS",
      "experience": 21
    },
    {
      "institutionName": "Neeta Marwaha's Multispeciality Dental Clinic",
      "address": "191, Sector B, Shakti Nagar, Habib Ganj",
      "City": "Bhopal",
      "State": "Madhya Pradesh",
      "pinCode": 462016,
      "personName": "Dr Neeta Marwaha",
      "specialities": "DENTAL SURGEON",
      "type": "BDS, MDS",
      "experience": 28
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "Dr. Manoj Agrawal",
      "specialities": "Oral & Maxillofacial Surgeon",
      "type": "M.D.S",
      "experience": 15
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "Dr. Namita Agrawal",
      "specialities": "Dental Surgeon",
      "type": "B.D.S",
      "experience": 14
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "Dr. Pranav Verma",
      "specialities": "Prosthodontist",
      "type": "M.D.S",
      "experience": 5
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "Dr. Ankur Nanda",
      "specialities": "Prosthodontist",
      "type": "M.D.S",
      "experience": 2
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "Dr. Arun Gupta",
      "specialities": "Orthodontist",
      "type": "M.D.S",
      "experience": 6
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "Dr. Supriti Dutta",
      "specialities": "Dental Surgeon",
      "type": "B.D.S",
      "experience": 11
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "Dr. Abeer Mishra",
      "specialities": "ENDODONTIST",
      "type": "M.D.S",
      "experience": 3
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "Dr. Shipra Prasad",
      "specialities": "Dental Surgeon",
      "type": "B.D.S",
      "experience": 5
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "Dr. Shubham",
      "specialities": "Dental Surgeon",
      "type": "B.D.S",
      "experience": 2
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "Dr. Sonal",
      "specialities": "Dental Surgeon",
      "type": "B.D.S",
      "experience": 3
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "Dr. Shiwani",
      "specialities": "Pidodontist",
      "type": "M.D.S",
      "experience": 1
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "Dr. Minal",
      "specialities": "Periodonties",
      "type": "M.D.S",
      "experience": 3
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "DR. ANKITA",
      "specialities": "Dental Surgeon",
      "type": "B.D.S",
      "experience": 6
    },
    {
      "institutionName": "Namman Hospital",
      "address": "25,star enclave above navdya sweets shankar nagar main road raipur c.g",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492007,
      "personName": "DR. Saniya Khan",
      "specialities": "Dental Surgeon",
      "type": "B.D.S",
      "experience": 1
    },
    {
      "institutionName": "COSMODONT Dental Clinic - Advanced Dental, Aesthetic, Implant and Laser clinic",
      "address": "1/246, Viram Khand 1, Gomtinagar, Lucknow, U.P.",
      "City": "Lucknow",
      "State": "Uttar Pradesh",
      "pinCode": 226010,
      "personName": "Dr. Utkarsh Singh",
      "specialities": "Periodontics and Implantology",
      "type": "BDS,MHA,PGCOD",
      "experience": 5
    },
    {
      "institutionName": "Kansal dental clinic and orthodontic centre",
      "address": "142/6,Nai sarak tiraha shastri nagar meerut",
      "City": "Meerut",
      "State": "Uttar Pradesh",
      "pinCode": 250002,
      "personName": "Dr. Puneet Kansal",
      "specialities": "Orthodontist",
      "type": "BDS",
      "experience": 22
    },
    {
      "institutionName": "Elite dental clinic",
      "address": "Frst floor, milan plaza, stratchey road",
      "City": "Allahabad",
      "State": "Uttar pradesh",
      "pinCode": 211001,
      "personName": "Dr. Abhishek Srivastava",
      "specialities": "Implantologist",
      "type": "BDS",
      "experience": 13
    },
    {
      "institutionName": "Elite dental clinic",
      "address": "Frst floor, milan plaza, stratchey road",
      "City": "Allahabad",
      "State": "Uttar pradesh",
      "pinCode": 211001,
      "personName": "Dr. Devanshee Srivastava",
      "specialities": "DENTAL SURGEON",
      "type": "BDS",
      "experience": 12
    },
    {
      "institutionName": "Shrimal Dental Centre",
      "address": "Ground Floor, Shrimal Dental Centre, Shivay 136, near Acer Kids School,",
      "City": "Jaipur",
      "State": "Rajasthan",
      "pinCode": 302004,
      "personName": "Dr Ronak Shrimal",
      "specialities": "Implants and orthodontic",
      "type": "BDS",
      "experience": 14
    },
    {
      "institutionName": "Rathore Dental Clinic",
      "address": "Shop No- 754 Kachhiyana Chowk",
      "City": "Jabalpur",
      "State": "Madhya Pradesh",
      "pinCode": 482002,
      "personName": "Dr Maharishi Rathore",
      "specialities": "Dentist",
      "type": "BDS",
      "experience": 11
    },
    {
      "institutionName": "Ronak Dental Clinic",
      "address": "A-22,1st floor, Ravi Complex, New IPCL Rd",
      "City": "Vadodara",
      "State": "Gujarat",
      "pinCode": 390023,
      "personName": "DR RONAK SHAH",
      "specialities": "DENTAL SURGEON",
      "type": "BDS",
      "experience": 14
    },
    {
      "institutionName": "Dr.Natu' S Care N Cure Dental Clinic",
      "address": "Shop No. 7, BCC Vision Apartment, Aishbagh Rd",
      "City": "Lucknow",
      "State": "Uttar Pradesh",
      "pinCode": 226004,
      "personName": "Dr Priyanka Sehgal",
      "specialities": "Dentist",
      "type": "BDS, MDS",
      "experience": 12
    },
    {
      "institutionName": "Clinic Dental Fort",
      "address": "Bhatia Market (Near Dhanraj Sweets) , jaisalmer",
      "City": "Jaisalmer",
      "State": "Rajasthan",
      "pinCode": 345001,
      "personName": "Dr Deep Bhatia",
      "specialities": "Dentist",
      "type": "BDS, MDS",
      "experience": 5
    },
    {
      "institutionName": "Modern Dental Clinic",
      "address": "Shop no 1, surjit singh complex Main road niharika",
      "City": "Korba",
      "State": "Chhattisgarh",
      "pinCode": 495677,
      "personName": "Dr Shahbaz Alam",
      "specialities": "Dentist",
      "type": "BDS",
      "experience": 12
    },
    {
      "institutionName": "Malik Dental Clinic",
      "address": "UGF 6 Shri Pratap Plaza, Sector B.",
      "City": "Lucknow",
      "State": "Uttar Pradesh",
      "pinCode": 226012,
      "personName": "Dr. Tarun Malik",
      "specialities": "Dentist",
      "type": "BDS",
      "experience": 15
    },
    {
      "institutionName": "Aayush Dental Clinic And Orthodontic Care Centre",
      "address": "Meera Apartments, W Park Rd",
      "City": "Nagpur",
      "State": "Maharashtra",
      "pinCode": 440012,
      "personName": "Dr. Piyush Kothari",
      "specialities": "Orthodontist & Implantologist",
      "type": "BDS",
      "experience": 21
    },
    {
      "institutionName": "Aayush Dental Clinic And Orthodontic Care Centre",
      "address": "Meera Apartments, W Park Rd",
      "City": "Nagpur",
      "State": "Maharashtra",
      "pinCode": 440012,
      "personName": "Dr. Sarita Kothari",
      "specialities": "Implantologist",
      "type": "BDS, MDS",
      "experience": 20
    },
    {
      "institutionName": "Niva Dental",
      "address": "101,COPPER LEAF, NR PARSHWANATH JAIN TEMPLE BRTS STOP",
      "City": "Ahmedabad",
      "State": "GUJARAT",
      "pinCode": 380063,
      "personName": "Dr Rakesh Patel",
      "specialities": "Dentist",
      "type": "BDS,MDS",
      "experience": 13
    },
    {
      "institutionName": "Balaji Dental hospital",
      "address": "near Government Hospital",
      "City": "Pokhran",
      "State": "Rajasthan",
      "pinCode": 345021,
      "personName": "Dr. Rajendra Singh",
      "specialities": "Dentist",
      "type": "BDS, MDS",
      "experience": 14
    },
    {
      "institutionName": "Shree Mahavir Dental Clinic & Implant Center",
      "address": "Kejriwal complex Road no 1",
      "City": "Jhunjhunu",
      "State": "Rajasthan",
      "pinCode": 333001,
      "personName": "Dr.Anil Rao",
      "specialities": "Dentist",
      "type": "BDS, DNHE, MHA",
      "experience": 11
    },
    {
      "institutionName": "Meera Dental Clinic",
      "address": "2nd Floor, Rajmahal Road, Chandra Prabha",
      "City": "Vadodara",
      "State": "Gujarat",
      "pinCode": 390001,
      "personName": "Dr. Jayesh M Shah",
      "specialities": "Endodontist",
      "type": "BDS, ADA",
      "experience": 39
    },
    {
      "institutionName": "CITY DENTAL CARE ",
      "address": "SHOP NO. 1 HANUMAN CHOWK",
      "City": "BATHINDA",
      "State": "Punjab",
      "pinCode": 151001,
      "personName": "DR MRIDUL MAHAJAN",
      "specialities": "DENTAL SURGEON",
      "type": "BDS, MDS",
      "experience": 15
    },
    {
      "institutionName": "Panjwani Dental Clinic",
      "address": "Govt Hospital, Korba - Champa Rd",
      "City": "Purani Basti",
      "State": "Chhattisgarh",
      "pinCode": 495678,
      "personName": "Dr. Avinash Rathore",
      "specialities": "Oral And MaxilloFacial Surgeon",
      "type": "BDS",
      "experience": 4
    },
    {
      "institutionName": "Smile Care Dental Clinic & Kids Care",
      "address": "police station, Near Gurudwara,1st Floor, 32, Varruchi Marg",
      "City": "Ujjain",
      "State": "Madhya Pradesh",
      "pinCode": 456006,
      "personName": "Dr. Pradhuman Malik",
      "specialities": "Oral And MaxilloFacial Surgeon",
      "type": "BDS",
      "experience": 11
    },
    {
      "institutionName": "Smile Care Dental Clinic & Kids Care",
      "address": "police station, Near Gurudwara,1st Floor, 32, Varruchi Marg",
      "City": "Ujjain",
      "State": "Madhya Pradesh",
      "pinCode": 456006,
      "personName": "Dr. Abhilasha Malik",
      "specialities": "Cosmetic Dental Surgeon",
      "type": "BDS,MDS",
      "experience": 10
    },
    {
      "institutionName": "Arora Dental Clinic",
      "address": "Arora implant dental clinic KAIRON ROAD",
      "City": "Malout",
      "State": "Punjab",
      "pinCode": 152107,
      "personName": "Dr B K ARORA",
      "specialities": "Dental Surgeon and Implantologist",
      "type": "BDS,",
      "experience": 24
    },
    {
      "institutionName": "Root canals kids dentistry implant dentistry",
      "address": "103, 1st Floor, Sai Vastu Heights, Landmark: Near SBI Govind Garden Chowk",
      "City": "Pune",
      "State": "Maharashtra",
      "pinCode": 411027,
      "personName": "Dr Neha Bandewar",
      "specialities": "DENTAL SURGEON",
      "type": "BDS",
      "experience": 16
    },
    {
      "institutionName": "Dental Square",
      "address": "B - 22 ground floor Vatika town square 1",
      "City": "Gurugram",
      "State": "Haryana",
      "pinCode": 122012,
      "personName": "Dr Sarjit Kumar",
      "specialities": "DENTAL SURGEON",
      "type": "BDS",
      "experience": 14
    },
    {
      "institutionName": "Make my tooth dental clinic",
      "address": "shop no 15, Nandini complex,near Gudumba Thana,kursi Road",
      "City": "Lucknow",
      "State": "Uttar Pradesh",
      "pinCode": 226022,
      "personName": "Dr Rahul chaturvedi",
      "specialities": "Dentist",
      "type": "BDS",
      "experience": 14
    },
    {
      "institutionName": "Lush Aesthetic & Dental Care",
      "address": "House No. 2550",
      "City": "Faridabad",
      "State": "Haryana",
      "pinCode": 121002,
      "personName": "Dr. Neha Garg",
      "specialities": "Dentofacial cosmetic surgeon",
      "type": "BDS PDCR FMC FAM",
      "experience": 13
    },
    {
      "institutionName": "Vedanta Dental Clinic",
      "address": "532/1, new railway road",
      "City": "Gurgaon",
      "State": "Haryana",
      "pinCode": 122001,
      "personName": "Dr Mayank Nagpal",
      "specialities": "Implantologist and Periodontist",
      "type": "MDS",
      "experience": 12
    },
    {
      "institutionName": "Root Care Dental Clinic",
      "address": "Shop no 12 , First floor, B block Market",
      "City": "Gurgaon",
      "State": "Haryana",
      "pinCode": 122018,
      "personName": "Dr Naveen Yadav",
      "specialities": "Periodontist & Implantologist",
      "type": "MDS",
      "experience": 10
    },
    {
      "institutionName": "Dr .Jigar's Dental clinic",
      "address": "#23, Ozone Angan Flats , Near GSC Bank, Opp. Ramapir no Tekro, Nava wadaj, Ahmedabad -",
      "City": "Ahmedabad",
      "State": "Gujarat",
      "pinCode": 380013,
      "personName": "Dr Jigar L prajapati",
      "specialities": "General Dentistry",
      "type": "BDS",
      "experience": 8
    },
    {
      "institutionName": "City Dental Clinic & Implant Centre",
      "address": "Just Infront Of Indradhanush Cloth Store, Near Siddhidatri Mata Mandir Chuna Wali Gali, Nikasa Rd",
      "City": "Vidisha",
      "State": "Madhya Pradesh",
      "pinCode": 464001,
      "personName": "Dr Ankit Khurana",
      "specialities": "Dentist",
      "type": "BDS",
      "experience": 15
    },
    {
      "institutionName": "Let's smile dental & aesthetic center",
      "address": "plot no 3,block 4 ,ground floor, spring field colony",
      "City": "Faridabad",
      "State": "Haryana",
      "pinCode": 121003,
      "personName": "Dr. Neetu sanwaria",
      "specialities": "DENTAL SURGEON",
      "type": "BDS,MIDA",
      "experience": 10
    },
    {
      "institutionName": "Smile Dental Clinic",
      "address": "near Malik Hospital - An Advanced Multi Specialty & Truma Hosptial",
      "City": "Hansi",
      "State": "Haryana",
      "pinCode": 125033,
      "personName": "Dr. Vikas Berwal",
      "specialities": "Oral Surgeon & Implantologist",
      "type": "MDS",
      "experience": 10
    },
    {
      "institutionName": "Smile Dental Clinic",
      "address": "near Malik Hospital - An Advanced Multi Specialty & Truma Hosptial",
      "City": "Hansi",
      "State": "Haryana",
      "pinCode": 125033,
      "personName": "Dr. Anita Singh Berwal",
      "specialities": "DENTAL SURGEON",
      "type": "BDA, MIDA",
      "experience": 8
    },
    {
      "institutionName": "Smile Hub Dental & Maxillofacial Center",
      "address": "2/138 Vishesh khand gomati nagar",
      "City": "Lucknow",
      "State": "Uttar pradesh",
      "pinCode": 226010,
      "personName": "Dr Pravesh Kumar Singh",
      "specialities": "Maxillofacial & Oncosurgeon",
      "type": "BDS, MDS",
      "experience": 10
    },
    {
      "institutionName": "Raunak Dental Care",
      "address": "GF-33 shyam plaza main road raipur",
      "City": "Raipur",
      "State": "Chhattisgarh",
      "pinCode": 492004,
      "personName": "Dr Kajal Ganveer",
      "specialities": "Dentist",
      "type": "BDS",
      "experience": 2
    },
    {
      "institutionName": "BRACES AND KIDS DENTISTRY",
      "address": "OFFICE NO. 223, ZODIAC MALL",
      "City": "INDORE",
      "State": "MADHYA PRADESH",
      "pinCode": 452016,
      "personName": "Dr. Harshal Gajeshwar",
      "specialities": "ORTHODONTICS",
      "type": "M.D.S",
      "experience": 13
    },
    {
      "institutionName": "METRO DENTAL & IMPLANT CLINIC",
      "address": "465, KRISHNA NAGAR, NEAR BAJAJ MARRIAGE HOME, BHARATPUR, RAJASTHAN  ",
      "City": "BHARATPUR",
      "State": "RAJASTHAN",
      "pinCode": 321001,
      "personName": "DR ADIT SINGHAL",
      "specialities": "PERIODONTIST & IMPLANTOLOGIST",
      "type": "BDS, MDS",
      "experience": 15
    },
    {
      "institutionName": "Dr Sachdeva's Dental Studio",
      "address": "Metropole Cottage Estate",
      "City": "Shimla",
      "State": "Himachal Pradesh",
      "pinCode": 171001,
      "personName": "Dr. Aman Sachdeva",
      "specialities": "Implantologits & Cosmetic Dentist",
      "type": "MDS",
      "experience": 18
    },
    {
      "institutionName": "32 STARS THE DENTAL HUB ",
      "address": "D 38/83 OPPOSITE KSHEER SAGAR MAHAMOORGANJ VARANASI",
      "City": "VARANASI",
      "State": "UTTAR PRADESH",
      "pinCode": 221010,
      "personName": "DR.ROHIT SINGH",
      "specialities": "PROSTHODONTIST AND IMPLANTOLOGIST",
      "type": "MDS",
      "experience": 10
    },
    {
      "institutionName": "DENTAL PLUS",
      "address": "S9/471 C DENTAL PLUS Clinic, adjacent to PNB Bank ",
      "City": "Varanasi",
      "State": "Uttar Pradesh ",
      "pinCode": 221002,
      "personName": "Dr Siddharth Jaiswal ",
      "specialities": "Dentist",
      "type": "BDS",
      "experience": 10
    },
    {
      "institutionName": "V S Dental Clinic & Implant Center",
      "address": "Chota chowk, Shahjahanpur (U.P.) - 242001",
      "City": "Shahjahanpur ",
      "State": "Uttar Pradesh ",
      "pinCode": 242001,
      "personName": "Dr. Ankit Agarwal",
      "specialities": "Endodontist",
      "type": "MDS ",
      "experience": 10
    },
    {
      "institutionName": "Smile Center",
      "address": "UG-1, VIP Galleria, Above Dhiraj Sons Bhimrad,",
      "City": "Surat",
      "State": "Gujarat ",
      "pinCode": 395017,
      "personName": "Dr. Sanket P Shroff",
      "specialities": "ORTHODONTICS",
      "type": "BDS",
      "experience": 14
    },
    {
      "institutionName": "Smile Center",
      "address": "UG-1, VIP Galleria, Above Dhiraj Sons Bhimrad,",
      "City": "Surat",
      "State": "Gujarat ",
      "pinCode": 395017,
      "personName": "Dr. Binal S Shroff",
      "specialities": " IMPLANTOLOGIST",
      "type": "BDS",
      "experience": 14
    },
    {
      "institutionName": "Care Dental Clinic",
      "address": "SHOP NO 23, HOUSING BOARD COMPLEX, NAGPUR ROAD,",
      "City": "CHHINDWARA",
      "State": "MADHYA PRADESH",
      "pinCode": 480001,
      "personName": "Dr Nitin Kumar Shrivastava ",
      "specialities": "DENTAL SURGEON",
      "type": "B.D.S",
      "experience": 12
    },
    {
      "institutionName": "Sharma Dental Care",
      "address": "3538/7, Reghar Pura, Vishnu Mandir Marg",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110005,
      "personName": "Dr Amit Sharma",
      "specialities": " IMPLANTOLOGIST",
      "type": "BDS",
      "experience": 17
    },
    {
      "institutionName": "Dr. Pandita's Dental And Implant Center",
      "address": "c-5/2, Block E, Vashist Park",
      "City": "New Delhi",
      "State": "Delhi",
      "pinCode": 110046,
      "personName": "Dr Aashish pandit",
      "specialities": "Periodontics and implantology",
      "type": "MDS",
      "experience": 13
    },
    {
      "institutionName": "Royal Dental Care",
      "address": "97-D, Defence Colony",
      "City": "Kanpur",
      "State": "Uttar Pradesh ",
      "pinCode": 208010,
      "personName": "Dr. Mohd Aseel",
      "specialities": "Dentist",
      "type": "BDS",
      "experience": 10
    },
    {
      "institutionName": "MAHESHWARAM DENTAL CARE",
      "address": "209, Sukhdev Nagar Main road ",
      "City": "INDORE",
      "State": "MADHYA PRADESH",
      "pinCode": 452005,
      "personName": "Dr.Gaurav Mishra",
      "specialities": "Paediatric dentist",
      "type": "MDS",
      "experience": 13
    },
    {
      "institutionName": "Indra Dental Hospital",
      "address": "Gurudura Road, Shakti Nagar Colony",
      "City": "Dholpur",
      "State": "Rajasthan ",
      "pinCode": 328001,
      "personName": "Dr Prakhar Mangal",
      "specialities": "Dentist",
      "type": "BDS MDS",
      "experience": 10
    },
    {
      "institutionName": "Hassan Dental Clinic",
      "address": "5, Rasuliya Rd, Kanchan Nagar, Rasuliya Rd, Kanchan Nagar",
      "City": "Narmadapuram",
      "State": "Madhya Pradesh",
      "pinCode": 461001,
      "personName": "Dr Yakuta Hassan ",
      "specialities": "DENTAL SURGEON",
      "type": "BDS",
      "experience": 10
    },
    {
      "institutionName": "Marble Dentistry",
      "address": " 312, Orbit Plaza, Crossings Republik",
      "City": " Ghaziabad",
      "State": "Uttar Pradesh ",
      "pinCode": 201016,
      "personName": "Dr. Sanchita Mittal",
      "specialities": "DENTAL SURGEON",
      "type": "BDS",
      "experience": 7
    },
    {
      "institutionName": "Samir Dental Care & Advanced Implant Centre",
      "address": " H. No. Backside SBI, 37, Street No. 2",
      "City": "Jalandhar",
      "State": "Punjab ",
      "pinCode": 144002,
      "personName": "Dr. Samir Nayyar",
      "specialities": "Implantologist",
      "type": "BDS",
      "experience": 15
    },
    {
      "institutionName": "Clover Dental Solutions",
      "address": "Shop no.UGF-23, SUPERTECH MART, SUPERTECH ECO VILLAGE-2, Greater Noida W Rd, Eco Village 2 ",
      "City": "Ghaziabad",
      "State": "Uttar Pradesh ",
      "pinCode": 201309,
      "personName": "Dr. Umang Tripathi",
      "specialities": "Orthodontist",
      "type": "BDS",
      "experience": 8
    },
    {
      "institutionName": "FLAIR DENTAL ",
      "address": "G1 plot no 747, Shakti khand 3 Indirapuram",
      "City": "Ghaziabad",
      "State": "Uttar Pradesh ",
      "pinCode": 201014,
      "personName": "Dr Manisha Singh ",
      "specialities": "Dental surgeon ",
      "type": "BDS , PGDCC ",
      "experience": 10
    },
    {
      "institutionName": "Dental Arch Gurgaon",
      "address": "LGF-105 Sector 28 Golf course Road",
      "City": "Gurgaon",
      "State": "Haryana",
      "pinCode": 122002,
      "personName": "Dr. Anish Goyal",
      "specialities": "Prosthodontics and Implantologist",
      "type": "BDS , MDS ",
      "experience": 8
    },
    {
      "institutionName": "Dr Manoj Dental Clinic ",
      "address": "J292, basement, Saket, New Delhi 110017",
      "City": "Delhi",
      "State": "New Delhi",
      "pinCode": 110017,
      "personName": "Dr. Manoj Kumar Verma",
      "specialities": "Dental surgeon ",
      "type": "BDS",
      "experience": 19
    },
    {
      "institutionName": "Prayag dental care ",
      "address": "17 mukta vihar,ADA road naini prayagraj,near mukta vihar park ",
      "City": "Prayagraj",
      "State": "Uttar Pradesh ",
      "pinCode": 211009,
      "personName": "Dr S.K Pandey",
      "specialities": "Endodontics",
      "type": "BDS",
      "experience": 11
    },
    {
      "institutionName": "Moga Dental",
      "address": "Moga dental , opp punjab national bank ,amritsar road ,moga. ",
      "City": "Moga",
      "State": "Punjab",
      "pinCode": 142042,
      "personName": "Dr Arshdeep singh",
      "specialities": "Oral pathologist",
      "type": "MDS",
      "experience": 10
    },
    { "institutionName": "Dr.Gupta Dental Hub", "City": "Amritsar" },
    { "institutionName": "Dadoo Dental Clinic", "City": "Meerut" },
    {
      "institutionName": "Mishra Dental Clinic",
      "address": "Raj stationery, Mungeli Naka Ground, behind DSS complex",
      "City": "Bilaspur",
      "State": "Chhattisgarh",
      "pinCode": 495001,
      "personName": "Dr. Shreemohan Mishra",
      "specialities": "Prosthodontist",
      "type": "BDS",
      "experience": 10
    }
  ]
 module.exports = instiData;  