const Code1 = () => {
  return (
    <div className="p-10">
      <h1 className="text-5xl p-10 font-semibold font-serif">Privacy Policy</h1>
      <p className="text-left py-2 text-2xl">
        MediEnsure Private Limited (hereinafter referred to as "ME" / “we” /
        “us”) is committed towards protecting your personally identifiable
        information, including sensitive personal data (“Personal Information”)
        that’s collected by MediEnsure from you whilst you use our website
        and/or mobile application (collectively referred to as the “Website”).
      </p>
      <p className="text-left py-2 text-2xl">
        MediEnsure collects, processes and treats the Personal Information of
        its users in compliance with the provisions of the Information
        Technology Act, 2000 and the Information Technology (Reasonable Security
        and Procedures and Sensitive Personal Data or Information) Rules, 2011
        (“Data Protection Laws”), to the extent applicable for such Personal
        Information.
      </p>
      <p className="text-left py-2 text-2xl">
        This Privacy Policy represents the complete statement of MediEnsure ‘s
        practices with respect to the collection of Personal Information through
        the Website and how it’s used.
      </p>
      <p className="text-left py-2 text-2xl">
        Please read this Privacy Policy carefully before proceeding to use our
        Website. By using the Website, you agree to be legally bound by the
        terms and conditions of this Privacy Policy, which shall take effect
        immediately on your first use of the Website. If you don’t agree, then
        please do not continue to access or use the Website and do not complete
        the registration process on the Website.
      </p>

      <h1 className="text-4xl py-5 text-left font-medium font-serif">
        1. SCOPE OF THE PRIVACY POLICY
      </h1>
      <p className="text-left py-2 text-2xl">
        The purpose of this Privacy Policy is to outline and help you understand
        the various procedure followed by MediEnsure when collecting, storing,
        utilising, disclosing or otherwise dealing with any Personal
        Information.
      </p>
      <p className="text-left py-2 text-2xl">
        Further, the Website may contain hyperlinks to third-party websites or
        social media websites operated by parties other than MediEnsure which
        are developed by people that MediEnsure has no control over, this
        includes social media plug-ins. This Privacy Policy does not apply to
        the practices of such websites. Such other websites may place their own
        cookies on your computer/electronic device, collect data or solicit
        Personal Information. MediEnsure is accordingly not and shall not be
        deemed to be responsible in any way for the privacy practices of such
        websites.
      </p>
      <p className="text-left py-2 text-2xl">
        Any summary of this Privacy Policy generated by third party software or
        otherwise shall have no legal effect, shall not be binding on
        MediEnsure, shall not be relied upon in substitute for this Privacy
        Policy, and neither supersede nor modify this Privacy Policy.
      </p>

      <h1 className="text-4xl py-5 text-left font-medium font-serif">
        2. INFORMATION COLLECTED BY MEDIENSURE
      </h1>
      <p className="text-left py-2 text-2xl">
        MediEnsure primarily collects, receives and stores the Personal
        Information, as may be provided by you in the course of creating your
        account as well as accessing and using the services provided through the
        Website. With regard to creating an account and registering on the
        Website, MediEnsure would generally process your name, phone number,
        e-mail address, age, date of birth, medical information such as your
        health status, medical reports history, medication history, account
        information like user name, password, payment preferences, and device
        information such as time zone, uploaded images, location data, etc.
      </p>
      <p className="text-left py-2 text-2xl">
        Additionally, in the course of your visit to the Website, MediEnsure
        and/or the third parties with whom MediEnsure has contracted to provide
        services, may collect certain anonymous information from sources such as
        server log files, cookies and pixel tags. MediEnsure and/or the third
        parties may collect information concerning your access to and use of the
        services provided through the Website such as what buttons/options you
        click on, devices you use to access the Website, the device’s unique
        identifying number, operating system, device language, device region,
        device time zone, mobile network information, etc. MediEnsure uses
        cookies or other similar software to provide a safe, efficient and
        customized experience to our users, and provide services and features
        that most likely meet your needs. You can change your privacy
        preferences regarding the use of cookies and similar technologies if
        your browser/device permits, but certain features on the Website may be
        restricted, unavailable or unusable if you choose not to provide certain
        information.
      </p>
      <p className="text-left py-2 text-2xl">
        MediEnsure and/or third-party service providers and/or our partners may
        also use cookies to manage and measure the performance of advertisements
        displayed on or delivered through the Website. This helps MediEnsure as
        well as service providers and partners to provide more relevant
        advertising.
      </p>
      <p className="text-left py-2 text-2xl">
        MediEnsure also automatically receives and records information on
        MediEnsure’s web server logs from user’s device including the Internet
        Protocol (IP) address. MediEnsure records IP addresses for anonymous
        statistical purposes, administration of this Website and associated
        servers, and to improve MediEnsure’s services.
      </p>
      <p className="text-left py-2 text-2xl">
        If you do not wish to provide the Personal Information requested or
        provide consent for use of your Personal Information, where required, or
        withdraw your consent for use of the Personal Information collected,
        MediEnsure reserves the right not to provide services or to withdraw the
        services for which the information was sought/collected from you.
      </p>

      <h1 className="text-4xl py-5 text-left font-medium font-serif">
        3. PAYMENT RELATED INFORMATION
      </h1>
      <p className="text-left py-2 text-2xl">
        All payment transactions happen using Secure Server Software through
        third party payment gateways. MediEnsure does not have end to end
        control over such transactions, and shall in no way be responsible or
        liable for any loss or damage due to any disclosure of your payment
        related information.
      </p>
      <p className="text-left py-2 text-2xl">
        MediEnsure hereby disclaims all its liability and shall in no way be
        liable or responsible for any loss or damage caused to you on account of
        intentional or unintentional disclosure of any Personal Information
        concerning your account and/or any information with respect to any
        online payment transaction handled by third party payment gateways using
        the credit card/debit card/cash card/net-banking/mobile wallet/UPI, etc.
        and/or the payment verification process.
      </p>

      <h1 className="text-4xl py-5 text-left font-medium font-serif">
        4. USE AND DISCLOSURE OF COLLECTED INFORMATION
      </h1>
      <p className="text-left py-2 text-2xl">
        When any Personal Information is provided by you to MediEnsure in the
        course of your access to the Website, that information provided shall be
        used by MediEnsure and its service providers and partners, including
        hospitals and other healthcare providers, for the purposes of providing
        MediEnsure’s services (online and offline), fulfil our service
        obligations, conducting background screening, facilitating any customer
        requests, and carrying out activities connected with the running of our
        business such as personnel training, quality control, and service
        monitoring.
      </p>
      <p className="text-left py-2 text-2xl">
        In addition, MediEnsure also reserves the right to use your Personal
        Information to contact you and deliver information targeted to your
        interests, such as banner advertisements, notices, service offerings,
        communications, newsletters, SMS messages, etc., relevant to your
        interests and use of the Website. By accepting the Terms of Use and this
        Privacy Policy, you expressly agree to receive such information and
        communications. In case you do not wish to receive such information and
        communications, then we request you to kindly unsubscribe/opt out of the
        receipt of such information and communications.
      </p>
      <p className="text-left py-2 text-2xl">
        MediEnsure treats your Personal Information and your use of MediEnsure’s
        services as private and confidential and does not disclose your Personal
        Information to third parties, except as may be necessary to provide
        MediEnsure’s services, and under the following specific circumstances:
      </p>
      <p className="text-left py-2 text-2xl">
        1. To insurance companies, hospitals, physicians or other healthcare
        providers that provide services directly to you on our behalf. To enable
        them to do this and related activities such as billing, we may need to
        share your Personal Information, including access to your medical
        reports for diagnosis, treatment etc;
      </p>
      <p className="text-left py-2 text-2xl">
        2. To enforce the Terms of Use which are binding on all the users of the
        Website;
      </p>
      <p className="text-left py-2 text-2xl">
        3. To respond to summons, court orders, or legal process, or to
        establish or exercise our legal rights or defend against legal claims;
      </p>
      <p className="text-left py-2 text-2xl">
        4. To any governmental body as and when required under law.
      </p>

      <h1 className="text-4xl py-5 text-left font-medium font-serif">
        5. SECURITY OF PERSONAL INFORMATION
      </h1>
      <p className="text-left py-2 text-2xl">
        MediEnsure takes all reasonable steps to comply with the applicable laws
        to ensure that the Personal Information provided by you is stored in a
        secure environment protected from unauthorised access, modification,
        destruction or disclosure. To protect Personal Information against
        accidental or unlawful destruction, loss or modification and against
        unauthorised disclosure or access, MediEnsure has implemented robust
        security practices and standards to guard your information. We take
        appropriate organisational and technical security measures, which are
        commensurate with the nature and sensitivity of the data being
        protected, to protect your data against unauthorised disclosure or
        processing. We use a secure server to store the information you give us
        when you use or create an account on the Website and any Personal
        Information you provide us online is securely encrypted.
      </p>
      <p className="text-left py-2 text-2xl">
        While MediEnsure strives to protect your Personal Information at all
        times, MediEnsure cannot guarantee its absolute security and shall not
        be liable for any breach of security by an outside party. It is also
        important for you to protect against unauthorised access to your user
        name and password for your account and to your computer/electronic
        device. Be sure to sign off from your account on the Website in case you
        access your account from a shared computer/electronic device.
      </p>
      <p className="text-left py-2 text-2xl">
        MediEnsure would also like to caution its users about phishing attacks,
        wherein unscrupulous third parties seek to extract sensitive and
        confidential information from you by posing as a genuine website or by
        sending an e-mail misrepresenting it to be from a genuine source. Please
        be careful while dealing with and/or responding to such e-mails. If you
        receive such a message claiming to be from MediEnsure, then please do
        not reply to it and immediately bring it to our attention by contacting
        the Grievance Officer.
      </p>
      <p className="text-left py-2 text-2xl">
        MediEnsure does not sell, rent, loan, trade, lease or license any
        Personal Information collected from or provided by you for any
        commercial purposes.
      </p>

      <h1 className="text-4xl py-5 text-left font-medium font-serif">
        6. ACCESS TO YOUR PERSONAL INFORMATION
      </h1>
      <p className="text-left py-2 text-2xl">
        For information collected through the Website, users can send an e-mail
        or letter to the Grievance Officer to:
        <li>
          Access Personal Information that the Website has collected from the
          user through your access to and use of the services provided through
          the Website;
        </li>
        <li>Correct any factual errors in such Personal Information; or</li>
        <li>
          Request to have your Personal Information deleted from MediEnsure’s
          servers.
        </li>
        <li>
          To protect the privacy and security of our users, MediEnsure will take
          reasonable steps to verify your identity before granting you access to
          your Personal Information that is collected and maintained by
          MediEnsure
        </li>
      </p>

      <h1 className="text-4xl py-5 text-left font-medium font-serif">
        7. INFORMATION WE COLLECT FROM THIRD PARTIES
      </h1>
      <p className="text-left py-2 text-2xl">
        We will ordinarily collect your Personal Information from you directly.
        However, we may occasionally, request your Personal Information from
        certain third parties such as your physician, hospital, or any other
        healthcare provider, for purposes such as providing and improving our
        services, fulfilling our contractual obligations to you, billing,
        conducting background screening, and carrying out any other activity
        related or incidental thereto. By completing the registration process on
        the Website and the use of MediEnsure’s services, you hereby consent to
        such third parties sharing such Personal Information with MediEnsure,
        and MediEnsure collecting, processing and storing such information for
        the abovementioned purposes.
      </p>

      <h1 className="text-4xl py-5 text-left font-medium font-serif">
        8. AMENDMENTS TO THE POLICY
      </h1>
      <p className="text-left py-2 text-2xl">
        This Policy is based on current laws and regulations applicable in
        India, and may be revised in view of any changes in law in India, as
        applicable to MediEnsure. MediEnsure reserves the right to put out
        revisions/modifications to this Privacy Policy, and any of its other
        procedures concerning the treatment of information collected through the
        Website, without any prior notice. Any changes to this Privacy Policy
        will become effective upon posting of the revised Privacy Policy on the
        Website. Access/use of the Website following the posting of the Privacy
        Policy will be considered as your acceptance of the revised Privacy
        Policy.
      </p>

      <h1 className="text-4xl py-5 text-left font-mediumfont-serif">
        9. GRIEVANCE OFFICER
      </h1>
      <p className="text-left py-2 text-2xl">
        For any queries related to this Privacy Policy, correction of any
        Personal Information provided by you or for making a complaint about
        breach of privacy, you can contact the following official of MediEnsure,
        E-mail id: grievance@mediensure.in
      </p>

      <h1 className="text-4xl py-5 text-left font-medium font-serif">
        10. GOVERNING LAW AND DISPUTE RESOLUTION
      </h1>
      <p className="text-left py-2 text-2xl">
        This Privacy Policy shall be governed by the laws of India. Any and all
        disputes arising under or in relation to this Privacy Policy shall be
        subject to the exclusive jurisdiction of courts in Bengaluru.
      </p>
    </div>
  );
};

export default Code1;
